import { useEffect, useState } from 'react';
import { Avatar } from './Profile';
import { profileOptions, profileService } from './profileService';
import { discoveryService, findPeople, fitReasons } from './discoveryService';

const emptyFilters=()=>({query:'',courseId:'',skills:[],interests:[],goals:[]});
export default function Discovery({user,onMessage}) {
  const [people,setPeople]=useState([]),[viewer,setViewer]=useState(null),[filters,setFilters]=useState(emptyFilters),[selected,setSelected]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);setError('');try{const [profiles,me]=await Promise.all([discoveryService.list(),profileService.get(user)]);setPeople(profiles);setViewer(me);}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{load();},[user.id]);
  const courseName=id=>id==='business-dev'?'Business development':'Software development';
  function toggle(key,value){setFilters(f=>({...f,[key]:f[key].includes(value)?f[key].filter(v=>v!==value):[...f[key],value]}));}
  if(loading)return <section className="form-card" role="status">Loading your community…</section>;
  if(error)return <section className="form-card"><p role="alert">{error}</p><button className="secondary" onClick={load}>Try again</button></section>;
  if(selected)return <section><button className="back-link" onClick={()=>setSelected(null)}>← Back to discovery</button><div className="profile-title"><div><span className="eyebrow">COMMUNITY PROFILE · SAMPLE</span><h1>{selected.displayName}</h1><p>{courseName(selected.courseId)}</p></div><Avatar name={selected.displayName} large /></div><div className="profile-layout"><aside className="form-card"><h2 className="font-semibold mb-3">Why you might connect</h2><ul className="fit-list">{fitReasons(selected,viewer).map(reason=><li key={reason}>{reason}</li>)}</ul><p className="field-help mt-4">Based on profile information, not a compatibility score.</p></aside><div className="form-card profile-details"><h2>About me</h2><p>{selected.bio}</p>{[['skills','Skills I bring'],['interests','My interests'],['goals','Looking for']].map(([key,title])=><section key={key}><h2>{title}</h2><div className="profile-tags">{selected[key].map(value=><span key={value}>{value}</span>)}</div></section>)}<button className="primary mt-6" onClick={()=>onMessage(selected.id)}>Message {selected.displayName.split(" ")[0]}</button></div></div></section>;
  const results=findPeople(people,filters,user.id);
  return <section><div className="discovery-hero"><div><span className="eyebrow">BETTER IDEAS START WITH PEOPLE</span><h1>Find your kind of ambition.</h1><p className="intro">A complementary skill. A shared interest. The start of something good.</p></div><img src="/community-hero.webp" alt="Learners collaborating on a project" /></div><div className="profile-title"><div><h2 className="text-xl font-semibold">Meet your community</h2><p className="field-help">Fictional profiles · Fit reasons use your saved demo profile.</p></div><a href="#profile">Update your profile</a></div><div className="discovery-filters form-card"><div className="filter-top"><label>Search people, skills or interests<input value={filters.query} onChange={e=>setFilters(f=>({...f,query:e.target.value}))} placeholder="e.g. React or sustainability" /></label><label>Course<select value={filters.courseId} onChange={e=>setFilters(f=>({...f,courseId:e.target.value}))}><option value="">All courses</option><option value="software-dev">Software development</option><option value="business-dev">Business development</option></select></label><button className="secondary" onClick={()=>setFilters(emptyFilters())}>Clear filters</button></div><details><summary>Skills, interests and connection goals</summary>{[['skills','Skills'],['interests','Interests'],['goals','Connection goals']].map(([key,title])=><fieldset className="profile-options" key={key}><legend>{title}</legend><div className="option-grid">{profileOptions[key].map(value=><label className="option" key={value}><input type="checkbox" checked={filters[key].includes(value)} onChange={()=>toggle(key,value)}/>{value}</label>)}</div></fieldset>)}<p className="field-help">Matches any selected option within a group, and all selected groups.</p></details></div><p className="result-count" role="status">{results.length} {results.length===1?'person':'people'} found</p>{results.length?<div className="discovery-grid">{results.map(person=><article className="form-card person-card" key={person.id}><div className="flex items-center gap-3"><Avatar name={person.displayName}/><div><h3 className="font-semibold">{person.displayName}</h3><p className="field-help">{courseName(person.courseId)}</p></div></div><p>{person.bio}</p><div className="profile-tags">{person.skills.map(skill=><span key={skill}>{skill}</span>)}</div><p className="fit-summary">{fitReasons(person,viewer)[0]}</p><button className="secondary" onClick={()=>setSelected(person)}>View {person.displayName.split(' ')[0]}’s profile →</button></article>)}</div>:<div className="form-card"><h2 className="font-semibold">No profiles match these filters.</h2><p className="intro">Try fewer filters or another search.</p><button className="secondary" onClick={()=>setFilters(emptyFilters())}>Show all people</button></div>}</section>;
}
